-- Align patient/document access with direct assignments or any active
-- appointment-doctor relationship. Replacement history grants no access.

DROP POLICY IF EXISTS "Doctors can view assigned or replacement patients only" ON public.patients;
DROP POLICY IF EXISTS "Doctors can update their assigned or replacement/appointment patients" ON public.patients;
DROP POLICY IF EXISTS "Select patient_documents policy" ON public.patient_documents;
DROP POLICY IF EXISTS "Insert patient_documents policy" ON public.patient_documents;
DROP POLICY IF EXISTS "Update patient_documents policy" ON public.patient_documents;
DROP POLICY IF EXISTS "Delete patient_documents policy" ON public.patient_documents;
DROP POLICY IF EXISTS "Select patient_notes policy" ON public.patient_notes;
DROP POLICY IF EXISTS "Insert patient_notes policy" ON public.patient_notes;
DROP POLICY IF EXISTS "Select storage_objects policy" ON storage.objects;
DROP POLICY IF EXISTS "Insert storage_objects policy" ON storage.objects;
DROP POLICY IF EXISTS "Delete storage_objects policy" ON storage.objects;

CREATE POLICY "Doctors can view assigned or appointment patients" ON public.patients FOR SELECT TO authenticated USING ((EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_role = 'doctor'::user_role AND staff_active = true)) AND (id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true)));
CREATE POLICY "Doctors can update assigned or appointment patients" ON public.patients FOR UPDATE TO authenticated USING ((EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_role = 'doctor'::user_role AND staff_active = true)) AND (id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))) WITH CHECK ((EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_role = 'doctor'::user_role AND staff_active = true)) AND (id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true)));

CREATE POLICY "Select patient_documents policy" ON public.patient_documents FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (patient_id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR patient_id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))))));
CREATE POLICY "Insert patient_documents policy" ON public.patient_documents FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND staff_id = patient_documents.uploaded_by AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (patient_id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR patient_id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))))));
CREATE POLICY "Update patient_documents policy" ON public.patient_documents FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (patient_id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR patient_id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true)))))) WITH CHECK (file_name = btrim(file_name) AND char_length(file_name) BETWEEN 1 AND 255 AND file_name !~ '[[:cntrl:]]' AND EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (patient_id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR patient_id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))))));
CREATE POLICY "Delete patient_documents policy" ON public.patient_documents FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (patient_id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR patient_id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))))));

REVOKE UPDATE ON TABLE public.patient_documents FROM authenticated;
GRANT UPDATE (file_name) ON TABLE public.patient_documents TO authenticated;

CREATE POLICY "Select patient_notes policy" ON public.patient_notes FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (patient_id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR patient_id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))))));
CREATE POLICY "Insert patient_notes policy" ON public.patient_notes FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND staff_id = patient_notes.created_by AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (patient_id IN (SELECT pd.patient_id FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR patient_id IN (SELECT a.patient_id FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))))));

CREATE POLICY "Select storage_objects policy" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'patient-documents' AND EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (path_tokens[1] IN (SELECT pd.patient_id::text FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR path_tokens[1] IN (SELECT a.patient_id::text FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))))));
CREATE POLICY "Insert storage_objects policy" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'patient-documents' AND EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (path_tokens[1] IN (SELECT pd.patient_id::text FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR path_tokens[1] IN (SELECT a.patient_id::text FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))))));
CREATE POLICY "Delete storage_objects policy" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'patient-documents' AND EXISTS (SELECT 1 FROM public.get_auth_staff_profile() WHERE staff_active = true AND (staff_role = ANY (ARRAY['super_admin'::user_role, 'receptionist'::user_role]) OR (staff_role = 'doctor'::user_role AND (path_tokens[1] IN (SELECT pd.patient_id::text FROM public.patient_doctors pd WHERE pd.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile())) OR path_tokens[1] IN (SELECT a.patient_id::text FROM public.appointments a JOIN public.appointment_doctors ad ON ad.appointment_id = a.id WHERE ad.doctor_id = (SELECT staff_id FROM public.get_auth_staff_profile()) AND ad.is_active = true))))));
